// ==========================================
// DocSnapSummaryWriter
// The "simple" output. Turns the same rich
// JsonValue trees the HTML pages are built
// from into short, plain Markdown a person can
// skim in a minute and - more importantly - can
// paste straight into an AI assistant without
// blowing its context window.
//
// The full HTML site and data/*.json remain the
// "advanced" output: everything, every field,
// every nested array. These summaries are the
// deliberately-lossy counterpart: hierarchy plus
// custom-script configuration for Scenes, and a
// one-line-per-file inventory for asset folders.
// A small Scene lands in a few hundred lines
// instead of the tens of thousands the exhaustive
// JSON needs.
// ==========================================
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Text;
using AmirCollider.UnityDocSnap.Editor.Json;
using AmirCollider.UnityDocSnap.Editor.Manifest;

namespace AmirCollider.UnityDocSnap.Editor.Summary
{
    internal static class DocSnapSummaryWriter
    {
        // A single script never lists more than this many
        // fields, and a single folder never lists more than
        // this many files, so one pathological component or
        // folder can never blow the summary back up to the
        // size the simple output exists to avoid. The full
        // set is always in the HTML page / data JSON.
        private const int MaxFieldsPerScript = 60;
        private const int MaxFilesPerFolderSection = 80;
        private const int MaxStringLength = 100;

        // ==========================================
        // RenderScene
        // A Scene's summary: header stats, a compact
        // hierarchy (one line per GameObject, annotated
        // with its component types), then the serialized
        // configuration of every custom script - the part
        // that actually tells you how the Scene is wired.
        // ==========================================
        public static string RenderScene(JsonValue sceneData)
        {
            string sceneName = sceneData.Get("sceneName").AsString("Scene");
            JsonValue rootObjects = sceneData.Get("rootObjects");

            int componentCount = 0;
            int scriptCount = 0;
            int missingCount = 0;
            var missing = new List<string>();
            Walk(rootObjects, 0, (go, depth) =>
            {
                foreach (JsonValue comp in go.Get("components").Items)
                {
                    componentCount++;
                    if (comp.Get("isMissing").AsBool()) { missingCount++; missing.Add(go.Get("name").AsString("GameObject")); }
                    else if (comp.Get("isUserScript").AsBool()) { scriptCount++; }
                }
            });

            var sb = new StringBuilder(4096);
            sb.Append("# ").Append(Clean(sceneName)).Append(" — Scene\n\n");
            sb.Append("- **Path:** `").Append(Code(sceneData.Get("scenePath").AsString(""))).Append("`\n");
            sb.Append("- **Engine:** Unity ").Append(Clean(sceneData.Get("unityVersion").AsString("?"))).Append("\n");
            sb.Append("- **Exported:** ").Append(Clean(sceneData.Get("exportedUtc").AsString(""))).Append("\n");
            sb.Append("- **")
              .Append((int)sceneData.Get("totalGameObjects").AsNumber()).Append(" GameObjects** · **")
              .Append(componentCount).Append(" components** · **")
              .Append(scriptCount).Append(" custom scripts**");
            if (missingCount > 0) { sb.Append(" · **").Append(missingCount).Append(" missing scripts**"); }
            sb.Append("\n\n");
            sb.Append("> Simple summary generated by ").Append(DocSnapConstants.ToolName)
              .Append(". `*` marks your own scripts. The complete, every-field version is the HTML page and `data/")
              .Append(DocSnapConstants.SceneJsonPrefix).Append("…json`.\n\n");

            sb.Append("## Hierarchy\n\n");
            if (rootObjects.Items.Count == 0)
            {
                sb.Append("_This Scene has no root GameObjects._\n\n");
            }
            else
            {
                Walk(rootObjects, 0, (go, depth) => sb.Append(HierarchyLine(go, depth)));
                sb.Append("\n");
            }

            sb.Append("## Script Configuration\n\n");
            bool anyScripted = false;
            Walk(rootObjects, 0, (go, depth) =>
            {
                if (!HasUserScript(go)) { return; }
                anyScripted = true;
                sb.Append(ScriptConfigBlock(go));
            });
            if (!anyScripted)
            {
                sb.Append("_No custom scripts in this Scene._\n\n");
            }

            if (missing.Count > 0)
            {
                sb.Append("## Missing Scripts\n\n");
                sb.Append("These GameObjects reference a script Unity can no longer find:\n\n");
                foreach (string name in Distinct(missing)) { sb.Append("- ").Append(Clean(name)).Append("\n"); }
                sb.Append("\n");
            }

            sb.Append(Footer());
            return sb.ToString();
        }

        // ==========================================
        // HierarchyLine
        // One indented bullet: the GameObject's name, an
        // optional tag / inactive marker, and the list of
        // component types it carries (custom scripts get
        // a trailing '*').
        // ==========================================
        private static string HierarchyLine(JsonValue go, int depth)
        {
            var sb = new StringBuilder(96);
            for (int i = 0; i < depth; i++) { sb.Append("  "); }
            sb.Append("- ").Append(Clean(go.Get("name").AsString("GameObject")));

            string tag = go.Get("tag").AsString("Untagged");
            if (!string.Equals(tag, "Untagged", StringComparison.Ordinal)) { sb.Append(" `").Append(Code(tag)).Append("`"); }
            if (!go.Get("activeSelf").AsBool(true)) { sb.Append(" _(inactive)_"); }

            string comps = ComponentTypeList(go);
            if (!string.IsNullOrEmpty(comps)) { sb.Append(" — ").Append(comps); }
            sb.Append("\n");
            return sb.ToString();
        }

        // ==========================================
        // ComponentTypeList
        // Comma-separated component type names for the
        // hierarchy line. Custom scripts are marked '*',
        // missing scripts called out explicitly.
        // ==========================================
        private static string ComponentTypeList(JsonValue go)
        {
            var parts = new List<string>();
            foreach (JsonValue comp in go.Get("components").Items)
            {
                if (comp.Get("isMissing").AsBool()) { parts.Add("⚠ Missing Script"); continue; }
                string typeName = Clean(comp.Get("typeName").AsString("Component"));
                parts.Add(comp.Get("isUserScript").AsBool() ? typeName + "*" : typeName);
            }
            return string.Join(", ", parts.ToArray());
        }

        // ==========================================
        // ScriptConfigBlock
        // One GameObject's custom-script detail: a short
        // identity/transform header, then every user
        // script's serialized fields (compact, one line
        // each, capped).
        // ==========================================
        private static string ScriptConfigBlock(JsonValue go)
        {
            var sb = new StringBuilder(512);
            sb.Append("### ").Append(Clean(go.Get("name").AsString("GameObject"))).Append("\n");

            string tag = go.Get("tag").AsString("Untagged");
            string layer = go.Get("layerName").AsString("Default");
            sb.Append("`tag ").Append(Code(tag)).Append("` · `layer ").Append(Code(layer)).Append("` · ")
              .Append(go.Get("activeSelf").AsBool(true) ? "Active" : "Inactive").Append("  \n");

            JsonValue t = go.Get("transform");
            sb.Append("Pos ").Append(Vec(t.Get("localPosition")))
              .Append(" · Rot ").Append(Vec(t.Get("localEulerAngles")))
              .Append(" · Scale ").Append(Vec(t.Get("localScale"))).Append("\n\n");

            foreach (JsonValue comp in go.Get("components").Items)
            {
                if (comp.Get("isMissing").AsBool() || !comp.Get("isUserScript").AsBool()) { continue; }

                sb.Append("- **").Append(Clean(comp.Get("typeName").AsString("Script"))).Append("**");
                if (comp.Get("isBehaviour").AsBool()) { sb.Append(comp.Get("enabled").AsBool(true) ? " · ON" : " · OFF"); }
                sb.Append("\n");

                JsonValue fields = comp.Get("fields");
                int shown = 0;
                foreach (JsonValue field in fields.Items)
                {
                    if (shown >= MaxFieldsPerScript)
                    {
                        sb.Append("  - _…+").Append(fields.Items.Count - shown).Append(" more fields (see full export)_\n");
                        break;
                    }
                    string name = field.Has("label") ? field.Get("label").AsString("") : field.Get("name").AsString("");
                    sb.Append("  - ").Append(Clean(name)).Append(": ").Append(FormatValue(field)).Append("\n");
                    shown++;
                }
                if (fields.Items.Count == 0) { sb.Append("  - _(no serialized fields)_\n"); }
            }
            sb.Append("\n");
            return sb.ToString();
        }

        // ==========================================
        // RenderFolder
        // An asset folder's summary: the directory tree
        // with counts, then a one-line-per-file inventory
        // grouped by folder (name, type, and the single
        // most useful type-specific fact).
        // ==========================================
        public static string RenderFolder(JsonValue folderData)
        {
            string folderPath = folderData.Get("folderPath").AsString("Assets");
            int fileCount = (int)folderData.Get("fileCount").AsNumber();

            var filesByPath = new Dictionary<string, JsonValue>(StringComparer.OrdinalIgnoreCase);
            foreach (JsonValue file in folderData.Get("files").Items)
            {
                string path = file.Get("path").AsString("");
                if (!string.IsNullOrEmpty(path)) { filesByPath[path.Replace('\\', '/')] = file; }
            }

            var sb = new StringBuilder(4096);
            sb.Append("# ").Append(Clean(folderPath)).Append(" — Assets\n\n");
            sb.Append("- **").Append(fileCount).Append(" files**\n");
            sb.Append("- **Exported:** ").Append(Clean(folderData.Get("exportedUtc").AsString(""))).Append("\n\n");
            sb.Append("> Simple summary generated by ").Append(DocSnapConstants.ToolName)
              .Append(". Import settings and every field are in the HTML page and `data/")
              .Append(DocSnapConstants.FolderJsonPrefix).Append("…json`.\n\n");

            JsonValue tree = folderData.Get("folderTree");
            sb.Append("## Folder tree\n\n");
            FolderTreeLines(tree, 0, sb);
            sb.Append("\n");

            sb.Append("## Files\n\n");
            FolderFileSections(tree, filesByPath, sb);

            sb.Append(Footer());
            return sb.ToString();
        }

        // ==========================================
        // FolderTreeLines
        // The directory tree as an indented bullet list,
        // each folder annotated with its direct and total
        // file counts.
        // ==========================================
        private static void FolderTreeLines(JsonValue folder, int depth, StringBuilder sb)
        {
            int direct = (int)folder.Get("directFileCount").AsNumber();
            int total = (int)folder.Get("totalFileCount").AsNumber();
            for (int i = 0; i < depth; i++) { sb.Append("  "); }
            sb.Append("- ").Append(Clean(folder.Get("folderName").AsString("?"))).Append("/  (").Append(direct).Append(" direct");
            if (total != direct) { sb.Append(", ").Append(total).Append(" total"); }
            sb.Append(")\n");
            foreach (JsonValue child in folder.Get("subfolders").Items) { FolderTreeLines(child, depth + 1, sb); }
        }

        // ==========================================
        // FolderFileSections
        // Depth-first over the folder tree; every folder
        // that directly contains files gets a section with
        // one compact line per file.
        // ==========================================
        private static void FolderFileSections(JsonValue folder, Dictionary<string, JsonValue> filesByPath, StringBuilder sb)
        {
            JsonValue filePaths = folder.Get("filePaths");
            if (filePaths.Items.Count > 0)
            {
                sb.Append("### ").Append(Clean(folder.Get("folderPath").AsString("")))
                  .Append("  (").Append(filePaths.Items.Count).Append(" files)\n\n");

                int shown = 0;
                foreach (JsonValue p in filePaths.Items)
                {
                    JsonValue entry;
                    if (!filesByPath.TryGetValue(p.AsString(""), out entry)) { continue; }
                    if (shown >= MaxFilesPerFolderSection)
                    {
                        sb.Append("- _…+").Append(filePaths.Items.Count - shown).Append(" more files (see full export)_\n");
                        break;
                    }
                    sb.Append(FileLine(entry));
                    shown++;
                }
                sb.Append("\n");
            }
            foreach (JsonValue child in folder.Get("subfolders").Items) { FolderFileSections(child, filesByPath, sb); }
        }

        // ==========================================
        // FileLine
        // One file: name — Type · one key fact · size.
        // ==========================================
        private static string FileLine(JsonValue file)
        {
            var sb = new StringBuilder(96);
            sb.Append("- ").Append(Clean(file.Get("fileName").AsString("")))
              .Append(" — ").Append(Clean(file.Get("mainType").AsString("Asset")));

            if (file.Has("imageWidth"))
            {
                sb.Append(" · ").Append((int)file.Get("imageWidth").AsNumber()).Append("×").Append((int)file.Get("imageHeight").AsNumber());
            }
            else if (file.Has("audioInfo") && file.Get("audioInfo").Has("lengthSeconds"))
            {
                sb.Append(" · ").Append(FormatDuration(file.Get("audioInfo").Get("lengthSeconds").AsNumber()));
            }
            else if (file.Has("prefabGameObjectCount"))
            {
                sb.Append(" · ").Append((int)file.Get("prefabGameObjectCount").AsNumber()).Append(" objects");
            }
            else if (file.Has("scriptInfo") && file.Get("scriptInfo").Has("className"))
            {
                sb.Append(" · class ").Append(Clean(file.Get("scriptInfo").Get("className").AsString("")));
            }
            else if (file.Has("materialInfo"))
            {
                sb.Append(" · shader ").Append(Clean(file.Get("materialInfo").Get("shaderName").AsString("")));
            }

            if (file.Has("fileSizeBytes")) { sb.Append(" · ").Append(FormatBytes(file.Get("fileSizeBytes").AsNumber())); }
            sb.Append("\n");
            return sb.ToString();
        }

        // ==========================================
        // RenderSceneJson
        // The structured counterpart to RenderScene: the
        // same compact view (hierarchy + custom-script
        // configuration) as machine-readable JSON, printed
        // with the leaf-inlining writer so it stays a few
        // hundred lines. Field/container values are
        // summarised exactly as in the Markdown, never
        // expanded, so this can never blow back up to the
        // size of the exhaustive data/ JSON.
        // ==========================================
        public static string RenderSceneJson(JsonValue sceneData)
        {
            JsonValue rootObjects = sceneData.Get("rootObjects");

            int componentCount = 0, scriptCount = 0, missingCount = 0;
            var missing = new List<string>();
            Walk(rootObjects, 0, (go, depth) =>
            {
                foreach (JsonValue comp in go.Get("components").Items)
                {
                    componentCount++;
                    if (comp.Get("isMissing").AsBool()) { missingCount++; missing.Add(go.Get("name").AsString("GameObject")); }
                    else if (comp.Get("isUserScript").AsBool()) { scriptCount++; }
                }
            });

            var root = JsonValue.Obj();
            root.Set("kind", "scene-summary");
            root.Set("generatedBy", DocSnapConstants.ToolName + " v" + DocSnapConstants.Version);
            root.Set("scene", sceneData.Get("sceneName").AsString("Scene"));
            root.Set("path", sceneData.Get("scenePath").AsString(""));
            root.Set("unityVersion", sceneData.Get("unityVersion").AsString(""));
            root.Set("exportedUtc", sceneData.Get("exportedUtc").AsString(""));
            root.Set("totals", JsonValue.Obj()
                .Set("gameObjects", (int)sceneData.Get("totalGameObjects").AsNumber())
                .Set("components", componentCount)
                .Set("customScripts", scriptCount)
                .Set("missingScripts", missingCount));

            root.Set("hierarchy", HierarchyJson(rootObjects));
            root.Set("scripts", ScriptsJson(rootObjects));

            if (missing.Count > 0)
            {
                var missingArr = JsonValue.Arr();
                foreach (string name in Distinct(missing)) { missingArr.Add(JsonValue.Str(Clean(name))); }
                root.Set("missingScripts", missingArr);
            }

            return root.ToCompactString() + "\n";
        }

        // ==========================================
        // HierarchyJson
        // One compact node per GameObject: name, optional
        // tag / inactive flag, its component types as a
        // single joined string, and nested children. A
        // leaf is all-scalar, so the compact writer prints
        // it on one line.
        // ==========================================
        private static JsonValue HierarchyJson(JsonValue objects)
        {
            var arr = JsonValue.Arr();
            foreach (JsonValue go in objects.Items)
            {
                var node = JsonValue.Obj();
                node.Set("name", Clean(go.Get("name").AsString("GameObject")));

                string tag = go.Get("tag").AsString("Untagged");
                if (!string.Equals(tag, "Untagged", StringComparison.Ordinal)) { node.Set("tag", Clean(tag)); }
                if (!go.Get("activeSelf").AsBool(true)) { node.Set("active", false); }

                string comps = ComponentTypeList(go);
                if (!string.IsNullOrEmpty(comps)) { node.Set("components", comps); }

                JsonValue children = go.Get("children");
                if (children.Items.Count > 0) { node.Set("children", HierarchyJson(children)); }

                arr.Add(node);
            }
            return arr;
        }

        // ==========================================
        // ScriptsJson
        // A flat list of every GameObject that carries a
        // custom script, each with its transform and the
        // serialized fields of its user scripts (compact,
        // capped, mirroring the Markdown Script
        // Configuration section).
        // ==========================================
        private static JsonValue ScriptsJson(JsonValue rootObjects)
        {
            var arr = JsonValue.Arr();
            Walk(rootObjects, 0, (go, depth) =>
            {
                if (!HasUserScript(go)) { return; }

                var node = JsonValue.Obj();
                node.Set("gameObject", Clean(go.Get("name").AsString("GameObject")));

                string tag = go.Get("tag").AsString("Untagged");
                if (!string.Equals(tag, "Untagged", StringComparison.Ordinal)) { node.Set("tag", Clean(tag)); }
                node.Set("layer", Clean(go.Get("layerName").AsString("Default")));
                if (!go.Get("activeSelf").AsBool(true)) { node.Set("active", false); }

                JsonValue t = go.Get("transform");
                node.Set("position", NumArr(t.Get("localPosition")));
                node.Set("rotation", NumArr(t.Get("localEulerAngles")));
                node.Set("scale", NumArr(t.Get("localScale")));

                var compsArr = JsonValue.Arr();
                foreach (JsonValue comp in go.Get("components").Items)
                {
                    if (comp.Get("isMissing").AsBool() || !comp.Get("isUserScript").AsBool()) { continue; }

                    var c = JsonValue.Obj();
                    c.Set("type", Clean(comp.Get("typeName").AsString("Script")));
                    if (comp.Get("isBehaviour").AsBool()) { c.Set("enabled", comp.Get("enabled").AsBool(true)); }

                    var fields = JsonValue.Obj();
                    JsonValue fieldItems = comp.Get("fields");
                    int shown = 0;
                    foreach (JsonValue field in fieldItems.Items)
                    {
                        if (shown >= MaxFieldsPerScript)
                        {
                            fields.Set("…", "+" + (fieldItems.Items.Count - shown) + " more fields (see full export)");
                            break;
                        }
                        string name = field.Has("label") ? field.Get("label").AsString("") : field.Get("name").AsString("");
                        fields.Set(Clean(name), FormatValue(field));
                        shown++;
                    }
                    c.Set("fields", fields);
                    compsArr.Add(c);
                }
                node.Set("components", compsArr);
                arr.Add(node);
            });
            return arr;
        }

        // ==========================================
        // RenderFolderJson
        // The structured counterpart to RenderFolder: the
        // directory tree with counts, then a one-object-
        // per-file inventory grouped by folder. Each file
        // object is all-scalar, so it prints on one line.
        // ==========================================
        public static string RenderFolderJson(JsonValue folderData)
        {
            var filesByPath = new Dictionary<string, JsonValue>(StringComparer.OrdinalIgnoreCase);
            foreach (JsonValue file in folderData.Get("files").Items)
            {
                string path = file.Get("path").AsString("");
                if (!string.IsNullOrEmpty(path)) { filesByPath[path.Replace('\\', '/')] = file; }
            }

            var root = JsonValue.Obj();
            root.Set("kind", "folder-summary");
            root.Set("generatedBy", DocSnapConstants.ToolName + " v" + DocSnapConstants.Version);
            root.Set("folder", folderData.Get("folderPath").AsString("Assets"));
            root.Set("files", (int)folderData.Get("fileCount").AsNumber());
            root.Set("exportedUtc", folderData.Get("exportedUtc").AsString(""));

            root.Set("tree", FolderTreeJson(folderData.Get("folderTree")));

            var sections = JsonValue.Arr();
            FolderFileSectionsJson(folderData.Get("folderTree"), filesByPath, sections);
            root.Set("byFolder", sections);

            return root.ToCompactString() + "\n";
        }

        private static JsonValue FolderTreeJson(JsonValue folder)
        {
            var node = JsonValue.Obj();
            node.Set("name", Clean(folder.Get("folderName").AsString("?")));
            node.Set("direct", (int)folder.Get("directFileCount").AsNumber());
            node.Set("total", (int)folder.Get("totalFileCount").AsNumber());
            JsonValue subs = folder.Get("subfolders");
            if (subs.Items.Count > 0)
            {
                var childrenArr = JsonValue.Arr();
                foreach (JsonValue child in subs.Items) { childrenArr.Add(FolderTreeJson(child)); }
                node.Set("children", childrenArr);
            }
            return node;
        }

        private static void FolderFileSectionsJson(JsonValue folder, Dictionary<string, JsonValue> filesByPath, JsonValue sections)
        {
            JsonValue filePaths = folder.Get("filePaths");
            if (filePaths.Items.Count > 0)
            {
                var section = JsonValue.Obj();
                section.Set("folder", Clean(folder.Get("folderPath").AsString("")));
                var filesArr = JsonValue.Arr();
                int shown = 0;
                foreach (JsonValue p in filePaths.Items)
                {
                    JsonValue entry;
                    if (!filesByPath.TryGetValue(p.AsString(""), out entry)) { continue; }
                    if (shown >= MaxFilesPerFolderSection)
                    {
                        filesArr.Add(JsonValue.Obj().Set("name", "…+" + (filePaths.Items.Count - shown) + " more files (see full export)"));
                        break;
                    }
                    filesArr.Add(FileJson(entry));
                    shown++;
                }
                section.Set("files", filesArr);
                sections.Add(section);
            }
            foreach (JsonValue child in folder.Get("subfolders").Items) { FolderFileSectionsJson(child, filesByPath, sections); }
        }

        private static JsonValue FileJson(JsonValue file)
        {
            var node = JsonValue.Obj();
            node.Set("name", Clean(file.Get("fileName").AsString("")));
            node.Set("type", Clean(file.Get("mainType").AsString("Asset")));

            if (file.Has("imageWidth"))
            {
                node.Set("dimensions", (int)file.Get("imageWidth").AsNumber() + "×" + (int)file.Get("imageHeight").AsNumber());
            }
            else if (file.Has("audioInfo") && file.Get("audioInfo").Has("lengthSeconds"))
            {
                node.Set("duration", FormatDuration(file.Get("audioInfo").Get("lengthSeconds").AsNumber()));
            }
            else if (file.Has("prefabGameObjectCount"))
            {
                node.Set("objects", (int)file.Get("prefabGameObjectCount").AsNumber());
            }
            else if (file.Has("scriptInfo") && file.Get("scriptInfo").Has("className"))
            {
                node.Set("class", Clean(file.Get("scriptInfo").Get("className").AsString("")));
            }
            else if (file.Has("materialInfo"))
            {
                node.Set("shader", Clean(file.Get("materialInfo").Get("shaderName").AsString("")));
            }

            if (file.Has("fileSizeBytes")) { node.Set("size", FormatBytes(file.Get("fileSizeBytes").AsNumber())); }
            return node;
        }

        private static JsonValue NumArr(JsonValue v)
        {
            return JsonValue.Arr()
                .Add(JsonValue.Num(v.Get("x").AsNumber()))
                .Add(JsonValue.Num(v.Get("y").AsNumber()))
                .Add(JsonValue.Num(v.Get("z").AsNumber()));
        }

        // ==========================================
        // RenderProjectIndex
        // The one file to hand someone (or an AI) first:
        // what this output folder is, which two forms it
        // comes in, and a link to every Scene / folder
        // summary. Built straight from the manifest so it
        // is refreshed cheaply on every single export.
        // ==========================================
        public static string RenderProjectIndex(ManifestState manifest)
        {
            int totalGameObjects = 0;
            foreach (ManifestSceneEntry s in manifest.scenes) { totalGameObjects += s.gameObjectCount; }
            int totalFiles = 0;
            foreach (ManifestFolderEntry f in manifest.assetFolders) { totalFiles += f.fileCount; }

            var sb = new StringBuilder(2048);
            sb.Append("# ").Append(Clean(manifest.projectName)).Append(" — ").Append(DocSnapConstants.ToolName).Append("\n\n");
            sb.Append("Unity ").Append(Clean(manifest.unityVersion))
              .Append(" · last export ").Append(Clean(manifest.lastUpdatedUtc))
              .Append(" · ").Append(DocSnapConstants.ToolName).Append(" v").Append(DocSnapConstants.Version).Append("\n\n");

            sb.Append("This export comes in two forms:\n\n");
            sb.Append("- **Simple (give this to an AI)** — the short files in **`").Append(DocSnapConstants.SummarySubFolder)
              .Append("/`**, linked below. Each Scene / folder has a readable `.md` and a structured `.json`, only a few hundred lines each.\n");
            sb.Append("- **Full (advanced)** — open **`").Append(DocSnapConstants.IndexFileName)
              .Append("`** in a browser for the complete interactive site, or read the raw **`")
              .Append(DocSnapConstants.DataSubFolder).Append("/…json`** for every single field.\n\n");

            sb.Append("## Scenes\n\n");
            if (manifest.scenes.Count == 0)
            {
                sb.Append("_None exported yet._\n\n");
            }
            else
            {
                foreach (ManifestSceneEntry s in manifest.scenes)
                {
                    sb.Append("- **").Append(Clean(s.sceneName)).Append("** — ").Append(s.gameObjectCount)
                      .Append(" GameObjects · [json](").Append(SceneSummaryJson(s.sceneName)).Append(")")
                      .Append(" · [md](").Append(SceneSummaryMarkdown(s.sceneName)).Append(")\n");
                }
                sb.Append("\n");
            }

            sb.Append("## Asset folders\n\n");
            if (manifest.assetFolders.Count == 0)
            {
                sb.Append("_None exported yet._\n\n");
            }
            else
            {
                foreach (ManifestFolderEntry f in manifest.assetFolders)
                {
                    sb.Append("- **").Append(Clean(f.folderPath)).Append("** — ").Append(f.fileCount)
                      .Append(" files · [json](").Append(FolderSummaryJson(f.folderKey)).Append(")")
                      .Append(" · [md](").Append(FolderSummaryMarkdown(f.folderKey)).Append(")\n");
                }
                sb.Append("\n");
            }

            sb.Append("## Totals\n\n");
            sb.Append("- ").Append(manifest.scenes.Count).Append(" scenes · ").Append(totalGameObjects).Append(" GameObjects\n");
            sb.Append("- ").Append(manifest.assetFolders.Count).Append(" asset folders · ").Append(totalFiles).Append(" files\n\n");

            sb.Append(Footer());
            return sb.ToString();
        }

        // ==========================================
        // Summary output paths
        // Every simple summary lives in the summary/
        // folder, named with the same self-describing
        // prefixes as the data JSON: "scene-<Name>" and
        // "folder-<Key>", one .md and one .json each.
        // ==========================================
        public static string SceneSummaryMarkdown(string sceneName)
        {
            return DocSnapConstants.SummarySubFolder + "/" + DocSnapConstants.SceneJsonPrefix + sceneName + DocSnapConstants.SummaryMarkdownExtension;
        }

        public static string SceneSummaryJson(string sceneName)
        {
            return DocSnapConstants.SummarySubFolder + "/" + DocSnapConstants.SceneJsonPrefix + sceneName + DocSnapConstants.SummaryJsonExtension;
        }

        public static string FolderSummaryMarkdown(string folderKey)
        {
            return DocSnapConstants.SummarySubFolder + "/" + DocSnapConstants.FolderJsonPrefix + folderKey + DocSnapConstants.SummaryMarkdownExtension;
        }

        public static string FolderSummaryJson(string folderKey)
        {
            return DocSnapConstants.SummarySubFolder + "/" + DocSnapConstants.FolderJsonPrefix + folderKey + DocSnapConstants.SummaryJsonExtension;
        }

        // ==========================================
        // FormatValue
        // Compact, single-line, plain-text rendering of
        // one serialized field. Container kinds (arrays,
        // structs, polymorphic refs) are summarised rather
        // than expanded, which is what keeps a script's
        // configuration to one line per field no matter
        // how deeply nested the underlying data is.
        // ==========================================
        private static string FormatValue(JsonValue field)
        {
            string kind = field.Get("kind").AsString("raw");
            switch (kind)
            {
                case "int":
                case "float":
                    return FormatNumber(field.Get("value").AsNumber());
                case "bool":
                    return field.Get("value").AsBool() ? "true" : "false";
                case "string":
                    return QuoteString(field.Get("value").AsString(""));
                case "enum":
                    return Clean(field.Get("value").AsString(""));
                case "color":
                    return Clean(field.Get("value").AsString(""));
                case "layerMask":
                    return "mask " + (int)field.Get("value").AsNumber();
                case "objectRef":
                    return FormatRef(field);
                case "vector2":
                case "vector2int":
                    return Vec2(field.Get("value"));
                case "vector3":
                case "vector3int":
                case "quaternion":
                    return Vec(field.Get("value"));
                case "vector4":
                    return Vec4(field.Get("value"));
                case "rect":
                case "rectint":
                    {
                        JsonValue v = field.Get("value");
                        return "x " + FormatNumber(v.Get("x").AsNumber()) + ", y " + FormatNumber(v.Get("y").AsNumber())
                            + ", w " + FormatNumber(v.Get("width").AsNumber()) + ", h " + FormatNumber(v.Get("height").AsNumber());
                    }
                case "bounds":
                    {
                        JsonValue v = field.Get("value");
                        return "center " + Vec(v.Get("center")) + " size " + Vec(v.Get("size"));
                    }
                case "boundsint":
                    {
                        JsonValue v = field.Get("value");
                        return "pos " + Vec(v.Get("position")) + " size " + Vec(v.Get("size"));
                    }
                case "curve":
                    return "animation curve (" + (int)field.Get("value").Get("keyCount").AsNumber() + " keys)";
                case "gradient":
                    return "gradient (" + field.Get("value").Get("colorKeys").Items.Count + " color keys)";
                case "hash128":
                    return Clean(field.Get("value").AsString(""));
                case "exposedRef":
                    return field.Get("isNull").AsBool(true) ? "unresolved" : Clean(field.Get("targetName").AsString(""));
                case "managedRef":
                    return field.Get("isNull").AsBool() ? "None" : "{" + Clean(field.Get("typeName").AsString("")) + "}";
                case "generic":
                    {
                        int n = field.Get("fields").Items.Count;
                        return n == 0 ? "{}" : "{ " + n + " fields }";
                    }
                case "array":
                    {
                        int count = (int)field.Get("count").AsNumber();
                        return "[" + count + (field.Get("truncated").AsBool() ? "+" : "") + " items]";
                    }
                case "error":
                    return "error: " + Clean(field.Get("value").AsString(""));
                default:
                    return QuoteString(field.Get("value").AsString(""));
            }
        }

        // ==========================================
        // FormatRef
        // An object-reference field as "→ Name (Type)",
        // "None", or a missing-reference note.
        // ==========================================
        private static string FormatRef(JsonValue refNode)
        {
            if (refNode.Get("isMissing").AsBool()) { return "⚠ missing reference"; }
            if (refNode.Get("isNull").AsBool(true)) { return "None"; }
            string targetName = refNode.Get("targetName").AsString("");
            string name = string.IsNullOrEmpty(targetName) ? "(unnamed)" : Clean(targetName);
            return "→ " + name + " (" + Clean(refNode.Get("refType").AsString("Object")) + ")";
        }

        // ==========================================
        // Small formatting helpers
        // ==========================================
        private static bool HasUserScript(JsonValue go)
        {
            foreach (JsonValue comp in go.Get("components").Items)
            {
                if (!comp.Get("isMissing").AsBool() && comp.Get("isUserScript").AsBool()) { return true; }
            }
            return false;
        }

        private static void Walk(JsonValue objects, int depth, Action<JsonValue, int> visit)
        {
            foreach (JsonValue go in objects.Items)
            {
                visit(go, depth);
                Walk(go.Get("children"), depth + 1, visit);
            }
        }

        private static List<string> Distinct(List<string> input)
        {
            var seen = new HashSet<string>(StringComparer.Ordinal);
            var result = new List<string>();
            foreach (string s in input) { if (seen.Add(s)) { result.Add(s); } }
            return result;
        }

        private static string Vec2(JsonValue v)
        {
            return "(" + FormatNumber(v.Get("x").AsNumber()) + ", " + FormatNumber(v.Get("y").AsNumber()) + ")";
        }

        private static string Vec(JsonValue v)
        {
            return "(" + FormatNumber(v.Get("x").AsNumber()) + ", " + FormatNumber(v.Get("y").AsNumber())
                + ", " + FormatNumber(v.Get("z").AsNumber()) + ")";
        }

        private static string Vec4(JsonValue v)
        {
            return "(" + FormatNumber(v.Get("x").AsNumber()) + ", " + FormatNumber(v.Get("y").AsNumber())
                + ", " + FormatNumber(v.Get("z").AsNumber()) + ", " + FormatNumber(v.Get("w").AsNumber()) + ")";
        }

        private static string FormatNumber(double d)
        {
            if (double.IsNaN(d) || double.IsInfinity(d)) { return "0"; }
            if (d == Math.Floor(d) && Math.Abs(d) < 1e15) { return ((long)d).ToString(CultureInfo.InvariantCulture); }
            return d.ToString("0.######", CultureInfo.InvariantCulture);
        }

        private static string FormatBytes(double bytes)
        {
            string[] units = { "B", "KB", "MB", "GB" };
            double size = bytes;
            int u = 0;
            while (size >= 1024 && u < units.Length - 1) { size /= 1024; u++; }
            return size.ToString("0.#", CultureInfo.InvariantCulture) + " " + units[u];
        }

        private static string FormatDuration(double seconds)
        {
            if (seconds < 60) { return seconds.ToString("0.###", CultureInfo.InvariantCulture) + " s"; }
            int minutes = (int)(seconds / 60);
            double remainder = seconds - (minutes * 60);
            return minutes.ToString(CultureInfo.InvariantCulture) + ":" + remainder.ToString("00.#", CultureInfo.InvariantCulture);
        }

        // ==========================================
        // QuoteString
        // A string value wrapped in quotes, single-lined,
        // and truncated so one long serialized string can
        // never dominate the summary.
        // ==========================================
        private static string QuoteString(string s)
        {
            return "\"" + Truncate(Clean(s)) + "\"";
        }

        // ==========================================
        // Clean
        // Collapses newlines/tabs to spaces so every value
        // stays on its own single Markdown line.
        // ==========================================
        private static string Clean(string s)
        {
            if (string.IsNullOrEmpty(s)) { return ""; }
            var sb = new StringBuilder(s.Length);
            foreach (char c in s)
            {
                sb.Append(c == '\n' || c == '\r' || c == '\t' ? ' ' : c);
            }
            return sb.ToString().Trim();
        }

        // ==========================================
        // Code
        // Clean plus backtick removal, for values shown
        // inside inline `code` spans (a stray backtick
        // would otherwise close the span early).
        // ==========================================
        private static string Code(string s)
        {
            return Clean(s).Replace("`", "'");
        }

        private static string Truncate(string s)
        {
            if (string.IsNullOrEmpty(s) || s.Length <= MaxStringLength) { return s; }
            return s.Substring(0, MaxStringLength) + "…";
        }

        private static string Footer()
        {
            return "---\n\nGenerated by " + DocSnapConstants.ToolName + " v" + DocSnapConstants.Version
                + " · " + DocSnapConstants.GithubUrl + "\n";
        }
    }
}
