// ==========================================
// DocSnapRootPage
// The output root is no longer a single site - it
// is a shelf of versioned sites (V1.0.0, V1.0.1, …),
// each self-contained in its own folder. This
// renders the two small pages that live at the root:
//   • versions.html — a friendly picker listing every
//     export newest-first, each linking into its own
//     index.html;
//   • index.html — a tiny redirect to the newest one,
//     so a double-click on the root still lands on the
//     latest documentation.
// Both are stand-alone (no sidebar shell, no external
// files) and theme-aware via prefers-color-scheme.
// ==========================================
using System.Collections.Generic;
using System.Text;
using AmirCollider.UnityDocSnap.Editor.Export;

namespace AmirCollider.UnityDocSnap.Editor.Html
{
    internal static class DocSnapRootPage
    {
        // ==========================================
        // RenderRedirect — index.html at the root.
        // ==========================================
        public static string RenderRedirect(string newestVersion)
        {
            // A custom version name is free text a user typed, so it
            // can contain a space or an '&' and must be percent-
            // encoded before it becomes a URL - Escape() alone made
            // the attribute safe but left the link broken.
            string target = HtmlPageBuilder.Href(newestVersion + "/" + DocSnapConstants.IndexFileName);
            var sb = new StringBuilder(512);
            sb.Append("<!doctype html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n");
            sb.Append("<meta http-equiv=\"refresh\" content=\"0; url=").Append(target).Append("\">\n");
            sb.Append("<title>Unity DocSnap</title>\n</head>\n<body>\n");
            sb.Append("<p>Opening the latest export… <a href=\"").Append(target).Append("\">")
              .Append(HtmlPageBuilder.Escape(newestVersion + "/" + DocSnapConstants.IndexFileName)).Append("</a></p>\n");
            sb.Append("<p><a href=\"").Append(DocSnapConstants.RootVersionsFileName).Append("\">All versions</a></p>\n");
            sb.Append("</body>\n</html>\n");
            return sb.ToString();
        }

        // ==========================================
        // RenderVersions — versions.html at the root.
        // ==========================================
        public static string RenderVersions(VersionsState registry, string newestVersion)
        {
            // Newest first.
            var ordered = new List<VersionSnapshot>(registry.versions);
            ordered.Sort((a, b) => DocSnapVersioning.CompareVersions(b.version, a.version));

            var sb = new StringBuilder(4096);
            sb.Append("<!doctype html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n");
            sb.Append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
            sb.Append("<title>Unity DocSnap — Versions</title>\n");
            sb.Append("<style>").Append(RootCss).Append("</style>\n</head>\n<body>\n");
            sb.Append("<div class=\"wrap\">\n");
            sb.Append("<h1>🧋 Unity DocSnap — Versions</h1>\n");
            sb.Append("<p class=\"sub\">Every export is kept as its own snapshot. Open one below.</p>\n");

            if (ordered.Count == 0)
            {
                sb.Append("<p class=\"empty\">No exports yet.</p>\n");
            }
            else
            {
                sb.Append("<ul class=\"list\">\n");
                foreach (VersionSnapshot v in ordered)
                {
                    string href = HtmlPageBuilder.Href(v.version + "/" + DocSnapConstants.IndexFileName);
                    sb.Append("<li><a class=\"row\" href=\"").Append(href).Append("\">");
                    sb.Append("<span class=\"tag\">").Append(HtmlPageBuilder.Escape(v.version)).Append("</span>");
                    if (v.version == newestVersion) { sb.Append("<span class=\"latest\">latest</span>"); }
                    sb.Append("<span class=\"counts\">")
                      .Append(v.sceneCount).Append(" scenes · ")
                      .Append(v.assetCount).Append(" assets · ")
                      .Append(v.packageCount).Append(" pkgs");
                    if (v.packagesUpdatable > 0) { sb.Append(" · ").Append(v.packagesUpdatable).Append(" updatable"); }
                    if (v.hasBackup) { sb.Append(" · 📦 backup"); }
                    sb.Append("</span>");
                    sb.Append("<span class=\"when\">").Append(HtmlPageBuilder.Escape(v.exportedLocal))
                      .Append(" · ").Append(HtmlPageBuilder.Escape(v.timeZone)).Append("</span>");
                    sb.Append("</a></li>\n");
                }
                sb.Append("</ul>\n");
            }

            sb.Append("<p class=\"foot\">Generated by Unity DocSnap 🍰</p>\n");
            sb.Append("</div>\n</body>\n</html>\n");
            return sb.ToString();
        }

        // Deliberately its own small stylesheet rather than a link
        // to theme/style.css: this page lives at the output ROOT,
        // one level above every version folder, and must keep
        // working when a version folder is deleted or moved. It
        // mirrors the site's tokens so the two do not look like
        // different products.
        private const string RootCss = @"
:root{color-scheme:light;--bg:#fbfbfd;--card:#fff;--surface-2:#f5f5f8;--ink:#1d1b26;--soft:#64616f;--faint:#97949f;--line:#e4e3ec;--accent:#7c5cd6;--ok:#2f8f5b;--ok-soft:#e9f7ef;}
@media (prefers-color-scheme: dark){:root{color-scheme:dark;--bg:#131218;--card:#1a1922;--surface-2:#211f2b;--ink:#eceaf3;--soft:#a5a1b3;--faint:#797588;--line:#2e2c3a;--accent:#a78bfa;--ok:#6fd39b;--ok-soft:#17291f;}}
*{box-sizing:border-box;}
body{margin:0;background:var(--bg);color:var(--ink);font-family:system-ui,-apple-system,'Segoe UI',Roboto,sans-serif;font-size:14px;line-height:1.55;-webkit-font-smoothing:antialiased;}
.wrap{max-width:760px;margin:0 auto;padding:48px 22px 64px;}
h1{font-size:22px;font-weight:650;letter-spacing:-.01em;margin:0 0 4px;}
.sub{color:var(--soft);margin:0 0 24px;font-size:13px;}
.empty{color:var(--faint);}
.list{list-style:none;margin:0;padding:0;display:flex;flex-direction:column;gap:6px;}
.row{display:flex;align-items:center;flex-wrap:wrap;gap:10px;padding:12px 15px;border:1px solid var(--line);border-radius:10px;background:var(--card);color:var(--ink);text-decoration:none;transition:border-color .12s ease,background .12s ease;}
.row:hover{background:var(--surface-2);border-color:var(--accent);}
.tag{font-weight:650;font-size:15px;color:var(--accent);font-variant-numeric:tabular-nums;}
.latest{font-size:10px;font-weight:700;color:var(--ok);background:var(--ok-soft);border-radius:999px;padding:1px 8px;}
.counts{font-size:12px;color:var(--soft);}
.when{margin-inline-start:auto;font-size:11.5px;color:var(--faint);font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;direction:ltr;}
.foot{margin-top:32px;padding-top:14px;border-top:1px solid var(--line);color:var(--faint);font-size:12px;text-align:center;}
";
    }
}
