// ==========================================
// DocSnapRootPage
// The output root is no longer a single site - it
// is a shelf of versioned sites (V1.0.0, V1.0.1, …),
// each self-contained in its own folder. This
// renders the two small pages that live at the root:
//   • versions.html — a friendly picker listing every
//     export newest-first, each linking into its own
//     index.html;
//   • index.html — a tiny redirect to the newest one,
//     so a double-click on the root still lands on the
//     latest documentation.
// Both are stand-alone (no sidebar shell, no external
// files) and theme-aware via prefers-color-scheme.
// ==========================================
using System.Collections.Generic;
using System.Text;
using AmirCollider.UnityDocSnap.Editor.Export;

namespace AmirCollider.UnityDocSnap.Editor.Html
{
    internal static class DocSnapRootPage
    {
        // ==========================================
        // RenderRedirect — index.html at the root.
        // ==========================================
        public static string RenderRedirect(string newestVersion)
        {
            string target = HtmlPageBuilder.Escape(newestVersion) + "/" + DocSnapConstants.IndexFileName;
            var sb = new StringBuilder(512);
            sb.Append("<!doctype html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n");
            sb.Append("<meta http-equiv=\"refresh\" content=\"0; url=").Append(target).Append("\">\n");
            sb.Append("<title>Unity DocSnap</title>\n</head>\n<body>\n");
            sb.Append("<p>Opening the latest export… <a href=\"").Append(target).Append("\">").Append(target).Append("</a></p>\n");
            sb.Append("<p><a href=\"").Append(DocSnapConstants.RootVersionsFileName).Append("\">All versions</a></p>\n");
            sb.Append("</body>\n</html>\n");
            return sb.ToString();
        }

        // ==========================================
        // RenderVersions — versions.html at the root.
        // ==========================================
        public static string RenderVersions(VersionsState registry, string newestVersion)
        {
            // Newest first.
            var ordered = new List<VersionSnapshot>(registry.versions);
            ordered.Sort((a, b) => DocSnapVersioning.CompareVersions(b.version, a.version));

            var sb = new StringBuilder(4096);
            sb.Append("<!doctype html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n");
            sb.Append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
            sb.Append("<title>Unity DocSnap — Versions</title>\n");
            sb.Append("<style>").Append(RootCss).Append("</style>\n</head>\n<body>\n");
            sb.Append("<div class=\"wrap\">\n");
            sb.Append("<h1>🧋 Unity DocSnap — Versions</h1>\n");
            sb.Append("<p class=\"sub\">Every export is kept as its own snapshot. Open one below.</p>\n");

            if (ordered.Count == 0)
            {
                sb.Append("<p class=\"empty\">No exports yet.</p>\n");
            }
            else
            {
                sb.Append("<ul class=\"list\">\n");
                foreach (VersionSnapshot v in ordered)
                {
                    string href = HtmlPageBuilder.Escape(v.version) + "/" + DocSnapConstants.IndexFileName;
                    sb.Append("<li><a class=\"row\" href=\"").Append(href).Append("\">");
                    sb.Append("<span class=\"tag\">").Append(HtmlPageBuilder.Escape(v.version)).Append("</span>");
                    if (v.version == newestVersion) { sb.Append("<span class=\"latest\">latest</span>"); }
                    sb.Append("<span class=\"counts\">")
                      .Append(v.sceneCount).Append(" scenes · ")
                      .Append(v.assetCount).Append(" assets · ")
                      .Append(v.packageCount).Append(" pkgs");
                    if (v.packagesUpdatable > 0) { sb.Append(" · ").Append(v.packagesUpdatable).Append(" updatable"); }
                    if (v.hasBackup) { sb.Append(" · 📦 backup"); }
                    sb.Append("</span>");
                    sb.Append("<span class=\"when\">").Append(HtmlPageBuilder.Escape(v.exportedLocal))
                      .Append(" · ").Append(HtmlPageBuilder.Escape(v.timeZone)).Append("</span>");
                    sb.Append("</a></li>\n");
                }
                sb.Append("</ul>\n");
            }

            sb.Append("<p class=\"foot\">Generated by Unity DocSnap 🍰</p>\n");
            sb.Append("</div>\n</body>\n</html>\n");
            return sb.ToString();
        }

        private const string RootCss = @"
:root{--bg:#fffaf3;--card:#fff;--ink:#4a3b52;--soft:#8a7a92;--line:#f0dfe8;--pink:#ff8fa3;--mint:#8fd98c;}
@media (prefers-color-scheme: dark){:root{--bg:#1c1922;--card:#241f2d;--ink:#ece7f2;--soft:#b3a8c2;--line:#38313f;--pink:#ff86a0;--mint:#8fd98c;}}
*{box-sizing:border-box;}
body{margin:0;background:var(--bg);color:var(--ink);font-family:'Quicksand','Segoe UI',system-ui,sans-serif;line-height:1.6;}
.wrap{max-width:760px;margin:0 auto;padding:44px 22px 64px;}
h1{font-size:26px;margin:0 0 6px;}
.sub{color:var(--soft);margin:0 0 26px;}
.empty{color:var(--soft);font-style:italic;}
.list{list-style:none;margin:0;padding:0;display:flex;flex-direction:column;gap:10px;}
.row{display:flex;align-items:center;flex-wrap:wrap;gap:10px;padding:14px 18px;border:1px solid var(--line);border-radius:14px;background:var(--card);color:var(--ink);text-decoration:none;box-shadow:0 6px 20px rgba(0,0,0,.06);transition:transform .15s ease;}
.row:hover{transform:translateY(-2px);}
.tag{font-weight:700;font-size:18px;color:var(--pink);}
.latest{font-size:10.5px;font-weight:700;color:#fff;background:var(--mint);border-radius:999px;padding:2px 9px;}
.counts{font-size:12px;color:var(--soft);}
.when{margin-inline-start:auto;font-size:12px;color:var(--soft);font-family:'Space Mono',monospace;direction:ltr;}
.foot{margin-top:34px;color:var(--soft);font-size:12.5px;text-align:center;}
";
    }
}
